### ISSUE TITLE
FINAL DEPLOYMENT - HEROKU, GOOGLE CLASSROOM

### ISSUE THREAD

**Issue by mh610creative** [samleemcknight/cocktail_codex#14]

**Comment by mh610creative** [comment]
asked michael and brock if its a mistake that its listed as a bonus on the project 2 readme 11:40am thursday

**Comment by mh610creative** [comment]
IT IS REQUIRED TO DEPLOY TO HEROKU

**Comment by mh610creative** [comment]
- [x] MERGE MAIN/SUBMAIN Branches 
- [x] HEROKU Staying bonus but we're doing it
- [x] Google Classroom Turn in github project repo link

**Comment by mh610creative** [comment]
- [x] Reseed DB so none of our test entries and edits are there.

**Comment by samleemcknight** [comment]
will deploy tomorrow after final pass-through
