### ISSUE TITLE
BOOTSTRAP/CSS/UX DESIGN

### ISSUE THREAD

**Issue by mh610creative** [samleemcknight/cocktail_codex#18]

**Comment by samleemcknight** [comment]
This is something that I have already begun doing and something we should continue doing as we make the views.

**Comment by mh610creative** [comment]
Ok. That's fine. This to-do is to make sure we go back and add new or change any existing styling.

**Comment by mh610creative** [comment]
- [x] Switch Login Icon to other icon img, shouldn't be userAvatar

**Comment by mh610creative** [comment]
ok to use bootswatch per instructors

**Comment by mh610creative** [comment]
- [x] fix select checkbox off-flush
