### ISSUE TITLE
Create Sequelize Validations for DB

### ISSUE THREAD

**Issue by samleemcknight** [samleemcknight/cocktail_codex#2]
A couple models should have some sort of validation in place to ensure the right data is going in. Cocktails model should have validation for the url attribute and ingredient model should have validation for 'Y' or 'N' under the isAlcohol column

**Comment by mh610creative** [comment]
Made seed file v.2 and sent in slack

**Comment by samleemcknight** [comment]
seed files don't have to do with validation

**Comment by mh610creative** [comment]
Ok. This is actually two tasks then. Sorry about the confusion.

**Comment by mh610creative** [comment]
PUT RESTRICTOR ON INCOMPLETE SEARCH OR ENABLE FRAGMENT OF WORD SEARCH === VALIDATION
