### ISSUE TITLE
CODE VIEWS BY CONTROLLER CATEGORY - MAIN TASK, SEE CKL BELOW

### ISSUE THREAD

**Issue by samleemcknight** [samleemcknight/cocktail_codex#3]

**Comment by mh610creative** [comment]
This includes 2/23 plan to draft as many views as possible after routes are confirmed/locked in.

**Comment by mh610creative** [comment]
Starting on this now.

**Comment by samleemcknight** [comment]
-[] cocktails/favorites
-[] cocktails/search
-[] cocktials/:id (show)

**Comment by samleemcknight** [comment]
- [x] / (auth/login)
- [x] /signup (auth/signup)
- [x] cocktails/favorites (favorites.ejs)
- [x] cocktails/ (search.ejs)
- [x] cocktials/:id (show.ejs)

**Comment by mh610creative** [comment]
added pseudocode directions to every ejs file, made more wireframes, need more wireframes

**Comment by mh610creative** [comment]
I think we need one more partial for the returned search results, if not a partial, then another ejs file

**Comment by mh610creative** [comment]
combine main search and search by primary alcohol for bonus when we get there --- ties into to bonus functionality to do. wait until then.

**Comment by mh610creative** [comment]
- [x] CONDITIONAL STATEMENT CONTROL FLOW FOR NO RESULTS FOUND

**Comment by mh610creative** [comment]
- [x] CLEAR SELECTOR BUTTON FROM RADIOS CLICKED BY USER IN ERROR
- [x] CONDITIONAL STATEMENT TO MAKE ADD TO FAVORITES BUTTON APPEAR AFTER RESULTS FOUND

**Comment by mh610creative** [comment]
- [x] FIX JANKY POST ROUTE REDIRECT FROM WHEN USER ADDS TO FAVORITES
- [x] FIGURE OUT A WAY TO ADD MULTIPLE COCKTAILS TO FAVORITES AT ONCE

**Comment by mh610creative** [comment]
- [x] Allow partial searches from main search 
- [x] Prevent duplicating favorited drinks from search to user Favorites

**Comment by mh610creative** [comment]
- [x] Draft HTML for user to edit favorite cocktail view
- [x] Draft HTML for other one cocktail view?

**Comment by mh610creative** [comment]
The base functionality crashed this morning after I pulled the overnights.

**Comment by mh610creative** [comment]
Want to focus on finishing view and ensuring core functionality today so this thread + function over anything else.

**Comment by mh610creative** [comment]
Per discussion, we dont need 2 views for single cocktail, just the one and going with myCocktails/:id route + view

**Comment by mh610creative** [comment]
All views are roughly built, finalizing edit recipe functionality.

**Comment by mh610creative** [comment]
closed and moved one remaining to QA issue
