### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by samleemcknight** [samleemcknight/cocktail_codex#5]

**Comment by mh610creative** [comment]
- [x] Screengrab final views for Overview Section after Final Team Approval
- [x] Clarify Installation Instructions now that Heroku is being utilized
- [x] They have given two different templates of readme, verify what needs to be on there, going with P1 requirements for now

**Comment by mh610creative** [comment]
Instructors said Use Project 1 Template for Readme and Use Install Instructions for local host dev
