### ISSUE TITLE
Edit/Finalize Routes Diagram and Rough Draft of Code Snippets for Routes

### ISSUE THREAD

**Issue by samleemcknight** [samleemcknight/cocktail_codex#6]

**Comment by mh610creative** [comment]
Going to have draft of all required and bonus routes by lunch 2/23. need S to discuss/review before adding to my branch file and doing first commit.

**Comment by mh610creative** [comment]
Already have pull request to submain for all draft routes EXCEPT AUTH, need to compare Brock's template first.

**Comment by mh610creative** [comment]
created all drafted routes in auth.js, server.js, cocktails.js. ready to build views.
